# Generated by Django 4.1.3 on 2022-11-16 02:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GetInvolvedIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_header', models.CharField(blank=True, max_length=250, null=True)),
                ('volunteer_header', models.CharField(blank=True, max_length=250, null=True)),
                ('volunteer_description', wagtail.fields.RichTextField(blank=True)),
                ('hiring_header', models.CharField(blank=True, max_length=250, null=True)),
                ('hiring_button_text', models.CharField(blank=True, max_length=250, null=True)),
                ('stay_involved_header', models.CharField(blank=True, max_length=250, null=True)),
                ('stay_involved_description', wagtail.fields.RichTextField(blank=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
