# Generated by Django 4.1.3 on 2022-11-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_hero_cta_link_homepage_hero_cta_text_and_more'),
        ('impact', '0001_initial'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='impact_primary_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='impact.articlepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_secondary_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='impact.articlepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='impact_tertiary_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='impact.articlepage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='involvement_cta_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='involvement_cta_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='involvement_header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='involvement_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_cta_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_cta_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_header',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_media_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
