# Generated by Django 4.1.3 on 2022-11-16 02:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='IconLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('YT', 'YouTube'), ('IG', 'Instagram'), ('FB', 'Facebook')], default='IG', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('partner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('role', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('bio_text', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('BM', 'Board Member'), ('EMP', 'Employee'), ('DIR', 'Director')], default='EMP', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('affiliation', models.CharField(blank=True, max_length=250, null=True)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='AboutIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('splash_text', models.TextField(blank=True, null=True)),
                ('mission_header', models.CharField(blank=True, max_length=250, null=True)),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('team_header', wagtail.fields.RichTextField(blank=True)),
                ('partners_header', wagtail.fields.RichTextField(blank=True)),
                ('team_directors_subheader', models.CharField(blank=True, max_length=250, null=True)),
                ('team_board_subheader', models.CharField(blank=True, max_length=250, null=True)),
                ('team_staff_subheader', models.CharField(blank=True, max_length=250, null=True)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('splash_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
