# Generated by Django 4.1.3 on 2022-11-16 02:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailimages', '0024_index_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactDataCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.CharField(blank=True, max_length=250, null=True)),
                ('unit', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('category', models.CharField(choices=[('cts', 'Citizen Scientist'), ('gwf', 'Green Workforce'), ('csn', 'Climate Safe Neighborhood')], default='gwf', max_length=3)),
                ('cta_text', models.CharField(blank=True, max_length=250, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_header', models.CharField(blank=True, max_length=250, null=True)),
                ('hero_description', models.TextField(blank=True, null=True)),
                ('impact_cta_text', models.CharField(blank=True, max_length=250, null=True)),
                ('impact_cta_link', models.CharField(blank=True, max_length=250, null=True)),
                ('work_header', models.CharField(blank=True, max_length=250, null=True)),
                ('involvement_header', wagtail.fields.RichTextField(blank=True)),
                ('involvement_cta_text', models.CharField(blank=True, max_length=250, null=True)),
                ('involvement_cta_link', models.CharField(blank=True, max_length=250, null=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('impact_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('involvement_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProgramPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_header', models.CharField(blank=True, max_length=250, null=True)),
                ('hero_description', wagtail.fields.RichTextField(blank=True)),
                ('hero_cta_text', models.CharField(blank=True, max_length=250, null=True)),
                ('hero_cta_link', models.CharField(blank=True, max_length=250, null=True)),
                ('badge_header', models.CharField(blank=True, max_length=250, null=True)),
                ('secondary_header', models.CharField(blank=True, max_length=250, null=True)),
                ('article_cta_text', models.CharField(blank=True, max_length=250, null=True)),
                ('work_opportunity_header', models.CharField(blank=True, max_length=250, null=True)),
                ('volunteer_header', models.CharField(blank=True, max_length=250, null=True)),
                ('volunteer_description', wagtail.fields.RichTextField(blank=True)),
                ('hero_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_header_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('secondary_hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('volunteer_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
